import pyautogui
from time import sleep
import os


macro = []
macrotime = []
os.system('cls' if os.name == 'nt' else 'clear')
while True:
    print()
    sleep(0.05)
    print("█▀▀ ▄▀▄ █▀▀ ▀▄▀ █▄ ▄█ ▄▀▄ █▀▀ █▀█ █▀█ █▀▀")
    sleep(0.05)
    print("██▄ █▀█ ▄██  █  █ ▀ █ █▀█ █▄▄ █▀▄ █▄█ ▄██")
    sleep(0.05)
    print()
    sleep(0.05)
    print("Easy Macros by J1D1:")
    sleep(0.05)
    print()
    sleep(0.05)
    print("1. Available Keys")
    sleep(0.05)
    print("2. Create Macro")
    sleep(0.05)
    print("3. Run Macro")
    sleep(0.05)
    print("4. Delete Macro")
    print("5. Exit")
    sleep(0.05)
    selected_option_menu = input("Select an option (1-5): ")
    if selected_option_menu == "1":
        os.system('cls' if os.name == 'nt' else 'clear')
        sleep(0.05)
        print()
        sleep(0.05)
        print("█▀▀ ▄▀▄ █▀▀ ▀▄▀ █▄ ▄█ ▄▀▄ █▀▀ █▀█ █▀█ █▀▀")
        sleep(0.05)
        print("██▄ █▀█ ▄██  █  █ ▀ █ █▀█ █▄▄ █▀▄ █▄█ ▄██")
        sleep(0.05)
        print()
        sleep(0.05)
        print("Available keys:")
        sleep(0.05)
        print()
        sleep(0.05)
        print("   Any symbol/letter/number on your keyboard, ")
        sleep(0.05)
        print("   Enter, ")
        sleep(0.05)
        print("   Space, ")
        sleep(0.05)
        print("   Shift, ")
        sleep(0.05)
        print("   Ctrl, ")
        sleep(0.05)
        print("   Alt, ")
        sleep(0.05)
        print("   Tab, ")
        sleep(0.05)
        print("   Esc, ")
        sleep(0.05)
        print("   Backspace, ")
        sleep(0.05)
        print("   Delete, ")
        sleep(0.05)
        print("   Win")
        sleep(0.05)
        print()
        sleep(0.05)
        print("Arrow keys: ")
        sleep(0.05)
        print("   Up, ")
        sleep(0.05)
        print("   Down, ")
        sleep(0.05)
        print("   Left, ")
        sleep(0.05)
        print("   Right")
        sleep(0.05)
        print()
        sleep(0.05)
        input("Press Enter to return to the main menu...")
        os.system('cls' if os.name == 'nt' else 'clear')
    elif selected_option_menu == "2":
        os.system('cls' if os.name == 'nt' else 'clear')
        print()
        sleep(0.05)
        print("█▀▀ ▄▀▄ █▀▀ ▀▄▀ █▄ ▄█ ▄▀▄ █▀▀ █▀█ █▀█ █▀▀")
        sleep(0.05)
        print("██▄ █▀█ ▄██  █  █ ▀ █ █▀█ █▄▄ █▀▄ █▄█ ▄██")
        sleep(0.05)
        print()
        sleep(0.05)
        x = input("Press Enter to add a key to the macro, type 'exit' to quit or type 'done' when finished: ")
        sleep(0.05)
        while True:
            if x == "exit":
                print("Exiting...")
                macro.clear()
                macrotime.clear()
                break
            elif x == "done":
                print()
                print("Macro setup complete.")
                sleep(0.05)
                print()
                print(macro)
                sleep(0.05)
                print()
                print(macrotime)
                sleep(0.05)
                print()
                input("Press Enter to return to the main menu...")
                os.system('cls' if os.name == 'nt' else 'clear')
                break
            else:
                macrotime.append(float(input("Delay between keys (in seconds): ")))
                sleep(0.05)
                macro.append(input("Key to press: "))
                sleep(0.05)
                x = input("Add key, exit or done: ")
    elif selected_option_menu == "3":
        input("Press Enter to start the macro...")
        os.system('cls' if os.name == 'nt' else 'clear')
        print()
        sleep(0.05)
        print("█▀▀ ▄▀▄ █▀▀ ▀▄▀ █▄ ▄█ ▄▀▄ █▀▀ █▀█ █▀█ █▀▀")
        sleep(0.05)
        print("██▄ █▀█ ▄██  █  █ ▀ █ █▀█ █▄▄ █▀▄ █▄█ ▄██")
        sleep(0.05)
        print()
        sleep(0.05)
        print("Running macro...")
        for i in macro:
            sleep(macrotime[macro.index(i)])
            pyautogui.press(i)
        print()
        sleep(0.05)
        print("Macro complete.")
        sleep(0.05)
        print()
        sleep(0.05)
        input("Press Enter to return to the main menu...")
        os.system('cls' if os.name == 'nt' else 'clear')
    elif selected_option_menu == "4":
        print()
        print("Deleting macro...")
        macro.clear()
        macrotime.clear()
        sleep(0.05)
        print()
        print("Macro deleted.")
        sleep(0.05)
        print()
        input("Press Enter to continue...")
        os.system('cls' if os.name == 'nt' else 'clear')
    elif selected_option_menu == "5":
        print("Exiting...")
        exit()